const GOOGLE_REGISTER__REQUEST = "GOOGLE_REGISTER__REQUEST";
const GOOGLE_REGISTER__SUCCESS = "REGISTER__SUCCESS";
const GOOGLE_REGISTER__FAIL = "GOOGLE_REGISTER__FAIL";

const GOOGLE_LOGOUT__REQUEST = "GOOGLE_LOGOUT__REQUEST";
const GOOGLE_LOGOUT__SUCCESS = "GOOGLE_LOGOUT__SUCCESS";
const GOOGLE_LOGOUT__FAIL = "GOOGLE_LOGOUT__FAIL";


const CLEAR__MESSAGES = "CLEAR__MESSAGES";
const CLEAR__ERRORS = "CLEAR__ERRORS";

const BOTTOM_TAB__VISIBLE = "BOTTOM_TAB__VISIBLE";
const BOTTOM_TAB__HIDDEN = "BOTTOM_TAB__HIDDEN";

export {
    GOOGLE_REGISTER__REQUEST, GOOGLE_REGISTER__SUCCESS, GOOGLE_REGISTER__FAIL,
    GOOGLE_LOGOUT__REQUEST, GOOGLE_LOGOUT__SUCCESS, GOOGLE_LOGOUT__FAIL,
    
    CLEAR__MESSAGES, CLEAR__ERRORS,
    BOTTOM_TAB__VISIBLE, BOTTOM_TAB__HIDDEN
};